#!/usr/bin/python3
def raise_exception():
    fady = "fady"
    print("{:d}".format(fady / 5))
